stages:
  - test

include:
  project: mattermost/ci/mattermost-redux
  ref: master
  file: private.yml

cache:
  key:
    files:
      - package.json
    prefix: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn/
    - node_modules/

lint:
  stage: test
  image: $CI_REGISTRY/mattermost/ci/images/mattermost-build-webapp:20200829_node-10.22
  before_script:
    - yarn install
  script:
    - yarn run check
    - yarn run tsc

test:
  stage: test
  image: $CI_REGISTRY/mattermost/ci/images/mattermost-build-webapp:20200829_node-10.22
  before_script:
    - yarn install
  script:
    - yarn test
