stages:
  - test

include:
  project: mattermost/ci/mattermost-redux
  ref: master
  file: private.yml

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

lint:
  stage: test
  image: $CI_REGISTRY/mattermost/ci/images/mattermost-build-redux:20210125_node-11.3-1
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run check
    - npm run tsc

test:
  stage: test
  image: $CI_REGISTRY/mattermost/ci/images/mattermost-build-redux:20210125_node-11.3-1
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm test
